#string, long, double, boolean
insert
# some generic resources
"name" sub resource datatype string;
"creation-date" sub resource datatype string;
"snb-id" sub resource datatype string;

# some basic entity-type with resource name
"tag" sub entity
    has-resource name,
    has-resource snb-id;

# person
"person" sub entity
    has-resource name,
    has-resource snb-id;

"acquaintance" sub role is-abstract;
"acquaintance1" sub acquaintance;
"acquaintance2" sub acquaintance;
"knows" sub relation
    has-role acquaintance1
    has-role acquaintance2
    has-resource creation-date;
person plays-role acquaintance1;
person plays-role acquaintance2;

# message
"content" sub resource datatype string;

"message" sub entity is-abstract
    has-resource creation-date
    has-resource content
    has-resource snb-id;

# relation likes
"liked" sub role;
"liker" sub role;
"likes" sub relation
    has-role liked
    has-role liker
    has-resource creation-date;
message plays-role liked;
person plays-role liker;

# relation writes
"written" sub role;
"writer" sub role;
"writes" sub relation
    has-role written
    has-role writer;
message plays-role written;
person plays-role writer;

"comment" sub message;

"reply-owner" sub role;
"reply-content" sub role;
"reply" sub relation
    has-role reply-content
    has-role reply-owner;
comment plays-role reply-content;
comment plays-role reply-owner;

# tag
"subject-tag" sub role;
"tagged-subject" sub role;
"tagging" sub relation
    has-role tagged-subject
    has-role subject-tag;
tag plays-role subject-tag;
message plays-role tagged-subject;
person plays-role tagged-subject;

